spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: ganesh
    password: admin@123
  jpa:
    show-sql: true

server:
  port: 4477

mybatis:
  type-handlers-package: com.example.mybatis_json_demo.typeHandler
