spring:
  datasource:
    url: jdbc:h2:mem:persons_db
    dr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 4466


mybatis:
  configuration:
